# Generated by Django 5.1.6 on 2025-02-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('truth', 'Правда'), ('dare', 'Действие')], max_length=100),
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
