# Generated by Django 5.1.6 on 2025-03-03 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_questioncategory_is_adult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Категория вопроса', 'verbose_name_plural': 'Категории вопросов'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('truth', 'Правда'), ('dare', 'Действие')], max_length=100, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Содержание вопроса'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Категория для взрослых (18+)'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.questioncategory', verbose_name='Категория вопроса'),
            preserve_default=False,
        ),
    ]
