# Generated by Django 5.1.6 on 2025-03-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='categories',
            new_name='category',
        ),
    ]
