# Generated by Django 5.1.6 on 2025-07-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Question Category', 'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['order'], 'verbose_name': 'Rule Page', 'verbose_name_plural': 'Rule Pages'},
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.questioncategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('truth', 'Truth'), ('dare', 'Dare')], max_length=100, verbose_name='Question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Adult category (18+)'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='text',
            field=models.TextField(verbose_name='Rule page content'),
        ),
    ]
