# Generated by Django 5.1.6 on 2025-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_question_question_type_delete_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
